### PR TITLE
Stop spamming for wait channel acquirement in orderer integration test

### LINKED ISSUE #2860: Integration test integration/raft/config_test.go often fails on Go 1.16.7
Integration test often fails in CI when using Go 1.16.7 at https://github.com/hyperledger/fabric/blob/main/integration/raft/config_test.go#L165.
The issue was not seen on prior Go version 1.15.7.
I cannot reproduce the issue in my environment on Go 1.16.7, it only appears in the Azure Pipeline execution.

The test expects orderer process to panic (and it does), however the test framework never receives notification that orderer process exited and eventually times out.

One (of many) occurrence here:
https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=39833&view=logs&jobId=4697389f-44ab-596f-b978-8083358e29e9&j=ea1ac65f-4899-54ff-1ca2-4326ac9b04bd&t=e554e2e7-1dcb-559d-af46-177f3e7010f2&s=435370a6-f89a-5869-4d11-90398ab6993a

```
2021-08-25T23:45:38.2465936Z [e][OrdererOrg.orderer] 2021-08-25 23:44:38.080 UTC 0020 INFO [orderer.commmon.multichannel] initSystemChannel -> Starting system channel 'systemchannel' with genesis block hash 1566701a79b2298c46b16b2cc6453dc0cee41e1dcfd755f9c45155a5016465bd and orderer type etcdraft
2021-08-25T23:45:38.2467041Z [e][OrdererOrg.orderer] 2021-08-25 23:44:38.080 UTC 0021 INFO [orderer.consensus.etcdraft] Start -> Starting Raft node channel=systemchannel node=1
2021-08-25T23:45:38.2468053Z [e][OrdererOrg.orderer] 2021-08-25 23:44:38.080 UTC 0022 INFO [orderer.common.cluster] Configure -> Entering, channel: systemchannel, nodes: []
2021-08-25T23:45:38.2468967Z [e][OrdererOrg.orderer] 2021-08-25 23:44:38.080 UTC 0023 INFO [orderer.common.cluster] Configure -> Exiting
2021-08-25T23:45:38.2469934Z [e][OrdererOrg.orderer] 2021-08-25 23:44:38.080 UTC 0024 INFO [orderer.consensus.etcdraft] start -> Starting raft node as part of a new channel channel=systemchannel node=1
2021-08-25T23:45:38.2470723Z [e][OrdererOrg.orderer] panic: election tick must be greater than heartbeat tick
2021-08-25T23:45:38.2471229Z [e][OrdererOrg.orderer] 
2021-08-25T23:45:38.2471700Z [e][OrdererOrg.orderer] goroutine 1 [running]:
2021-08-25T23:45:38.2473407Z [e][OrdererOrg.orderer] go.etcd.io/etcd/raft.newRaft(0xc00037e2c0, 0xa4506ceb90befffa)
2021-08-25T23:45:38.2474253Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/vendor/go.etcd.io/etcd/raft/raft.go:326 +0xef1
2021-08-25T23:45:38.2475033Z [e][OrdererOrg.orderer] go.etcd.io/etcd/raft.StartNode(0xc00037e2c0, 0xc0003ce3c0, 0x1, 0x1, 0xa3c481f234d6c922, 0x40d05f09435f9c79)
2021-08-25T23:45:38.2475728Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/vendor/go.etcd.io/etcd/raft/node.go:201 +0x45
2021-08-25T23:45:38.2476564Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*node).start(0xc00037e370, 0x1)
2021-08-25T23:45:38.2477315Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/consensus/etcdraft/node.go:73 +0x297
2021-08-25T23:45:38.2478006Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).Start(0xc00022c840)
2021-08-25T23:45:38.2478676Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:362 +0x1b5
2021-08-25T23:45:38.2479362Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/common/multichannel.(*ChainSupport).start(...)
2021-08-25T23:45:38.2480034Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/common/multichannel/chainsupport.go:120
2021-08-25T23:45:38.2480759Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).startChannels(0xc000459600)
2021-08-25T23:45:38.2481459Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/common/multichannel/registrar.go:177 +0xb5
2021-08-25T23:45:38.2482209Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).Initialize(0xc000459600, 0xc000474cc0)
2021-08-25T23:45:38.2482928Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/common/multichannel/registrar.go:147 +0x8e
2021-08-25T23:45:38.2483850Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(0xc00015a640, 0xc000452900, 0xc0000a4e00, 0x0, 0x0, 0xc000081c00, 0x398, 0x399, 0xc0000fe600, 0xf1, ...)
2021-08-25T23:45:38.2484655Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/common/server/main.go:828 +0x485
2021-08-25T23:45:38.2485264Z [e][OrdererOrg.orderer] github.com/hyperledger/fabric/orderer/common/server.Main()
2021-08-25T23:45:38.2485903Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/orderer/common/server/main.go:245 +0x10ef
2021-08-25T23:45:38.2486414Z [e][OrdererOrg.orderer] main.main()
2021-08-25T23:45:38.2486962Z [e][OrdererOrg.orderer] 	/home/vsts/work/1/fabric/cmd/orderer/main.go:15 +0x25
2021-08-25T23:45:38.2487173Z 
2021-08-25T23:45:38.2487518Z ------------------------------
2021-08-25T23:45:38.2487938Z • Failure [60.342 seconds]
2021-08-25T23:45:38.2488577Z EndToEnd reconfiguration and onboarding Invalid Raft config metadata [It] refuses to start orderer or rejects config update 
2021-08-25T23:45:38.2489211Z /home/vsts/work/1/fabric/integration/raft/config_test.go:146
2021-08-25T23:45:38.2489391Z 
2021-08-25T23:45:38.2489716Z   Timed out after 60.001s.
2021-08-25T23:45:38.2489958Z   Expected
2021-08-25T23:45:38.2490358Z       <<-chan error | len:1, cap:1>: 0xc000a84840
2021-08-25T23:45:38.2490774Z   to receive something.
2021-08-25T23:45:38.2490962Z 
2021-08-25T23:45:38.2491216Z   /home/vsts/work/1/fabric/integration/raft/config_test.go:165
2021-08-25T23:45:38.2491675Z ------------------------------
2021-08-25T23:53:49.0284685Z ••••••••••••••••••••
2021-08-25T23:53:49.0306463Z 
2021-08-25T23:53:49.0307909Z Summarizing 1 Failure:
2021-08-25T23:53:49.0308362Z 
2021-08-25T23:53:49.0309455Z [Fail] EndToEnd reconfiguration and onboarding Invalid Raft config metadata [It] refuses to start orderer or rejects config update 
2021-08-25T23:53:49.0310630Z /home/vsts/work/1/fabric/integration/raft/config_test.go:165
```

### PR DESCRIPTION
**Pull request by yacovm**
The code passes a function that returns a channel instead of the channel returned by that function.
As a result, the function is being polled thousands of times needlessly and thousands of channels
are being created, after which a goroutine per channel feeds a value into each of them.

Unfortunately, Gomega uses reflection based select on each of these channels, which is non-blocking,
meaning it just grabs a lock on the channel, and if the sender goroutine hasn't sent the item yet,
it returns false.

Since we pass in the Gomega.Eventually, a function (and not a channel), the reflection based receive is only attempted
once on each channel (out of the thousands created) and this creates a flake, because sometimes
we reach the timeout before one of the goroutines has a chance to obtain the lock on the channel
before the reflection based select obtains it, sees the channel buffer is empty, and the Gomega
attempt for that channel is then given up.

Resolves #2860 

Change-Id: I4417703d17e48afec50f46f3ae6b77a8e61a9be7
Signed-off-by: Yacov Manevich <yacovm@il.ibm.com>

### CODE REVIEW

File: integration/raft/config_test.go [hunk 1]
```diff
@@ -162,7 +162,7 @@ var _ = Describe("EndToEnd reconfiguration and onboarding", func() {
 			By("Starting orderer with malformed genesis block")
 			ordererRunner := network.OrdererGroupRunner()
 			process := ifrit.Invoke(ordererRunner)
-			Eventually(process.Wait, network.EventuallyTimeout).Should(Receive()) // orderer process should exit
+			Eventually(process.Wait(), network.EventuallyTimeout).Should(Receive()) // orderer process should exit
```
Comment (yacovm) [inline integration/raft/config_test.go:165]: I know it's a dead giveaway when in any other place in the code, we do `Wait()` and not `Wait`, but, I couldn't just push a PR without explaining why the current code is wrong.

**Comment by denyeart** [comment]
Wow, good catch and good explanation.
I guess line 211 has the same issue? (that's the only other occurrence I found)
https://github.com/hyperledger/fabric/blob/main/integration/raft/config_test.go#L211

**Comment by yacovm** [comment]
> Wow, good catch and good explanation.
> I guess line 211 has the same issue? (that's the only other occurrence I found)
> https://github.com/hyperledger/fabric/blob/main/integration/raft/config_test.go#L211

No because it should never receive, here it should receive. 
The other line polls a lot, but, under proper execution, none of the channels will ever have anything in them. 
Regardless I will change it.

**Review by C0rWin — APPROVED** [review]

**Comment by denyeart** [comment]
@Mergifyio backport release-2.3

**Comment by denyeart** [comment]
@Mergifyio backport release-2.2

**Comment by denyeart** [comment]
@Mergifyio backport release-1.4
