### PR TITLE
Retry logic for evaluate

### LINKED ISSUE #2913: Gateway: retry logic for evaluate method
Currently, the gateway's evaluate method will select a peer based on maximum block height in order to query the ledger.  If this fails due to connectivity reasons, then the error is returned to the client.
This enhancement will handle these errors by attempting to select an alternative peer, and retry the query.  If no peers can successfully process the query, then the error is returned to the client.
Note this logic won't apply to errors that are raised by the chaincode since it is assumed that all instances will return this same error (e.g. wrong number/type of arguments, etc).

### PR DESCRIPTION
**Pull request by andrew-coleman**
Modify the evaluate method to retry processing of a transaction proposal on another peer in the case of an error.

resolves #2913 

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

### CODE REVIEW

File: internal/pkg/gateway/registry.go [hunk 1]
```diff
@@ -205,21 +205,31 @@ func (reg *registry) evaluator(channel string, chaincode string, targetOrgs []st
...
-			evaluator = e[0].endorser
-			maxHeight = e[0].height
+		if es, ok := endorsersByOrg[org]; ok {
+			for _, e := range es {
+				if org == reg.localEndorser.mspid {
+					localOrgEndorsers = append(localOrgEndorsers, e)
+				} else {
+					otherOrgEndorsers = append(otherOrgEndorsers, e)
+				}
+			}
```
Comment (manish-sethi) [inline internal/pkg/gateway/registry.go]: For loop can be avoided

```suggestion
			if org == reg.localEndorser.mspid {
				localOrgEndorsers = es
			}else{
				otherOrgEndorsers = append(otherOrgEndorsers, es...)
			}
```

File: internal/pkg/gateway/api.go [hunk 2]
```diff
@@ -64,24 +64,41 @@ func (gs *Server) Evaluate(ctx context.Context, request *gp.EvaluateRequest) (*g
...
+			err = fmt.Errorf("error %d returned from chaincode %s on channel %s: %s", response.Status, chaincodeID, channel, response.Message)
+			endpointErr := errorDetail(endorser.endpointConfig, err)
+			errDetails = append(errDetails, endpointErr)
+			// this is a chaincode error response - don't retry
+			endorser = nil
+			response = nil
+		}
+	}
+	if endorser == nil || response == nil {
+		return nil, rpcError(codes.Aborted, "failed to evaluate transaction, see attached details for more info", errDetails...)
```
Comment (manish-sethi) [inline internal/pkg/gateway/api.go]: From the readability perspective, setting variables to some values and checking latter for clubbing all cases of return error is not a preferred way. The suggested way would be to check for return condition in both if clauses and return early.

**Review by manish-sethi — COMMENTED** [review]
LGTM - A couple cleanup comments

**Review by manish-sethi — APPROVED** [review]
