### PR TITLE
EndorsementTimeout should apply to each endorser

### LINKED ISSUE #292: Gateway will incorrectly close endorsers if endorsement timeout is reached
When running scenarios for peers being killed I occasionally see the following error
```
10 ABORTED: failed to collect enough transaction endorsements, see attached details for more info Details: [{\"address\":\"peer1.org3.example.com:11151\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org3MSP\"},{\"address\":\"peer0.org2.example.com:9051\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org2MSP\"},{\"address\":\"peer1.org2.example.com:9151\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org2MSP\"}]"
```

In the gateway logs I see
```
[36m2021-11-04 15:13:03.464 UTC 8a62 DEBU[0m [gateway] [36;1mfunc1[0m -> Endorse call to endorser failed channel=mychannel txid=4cc6982d9c5aea6f9a5e988dd9f834053353dd858f17f78f8f5b319be4183f34 numEndorsers=1 endorserAddress=peer1.org3.example.com:11151 endorserMspid=Org3MSP error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
[34m2021-11-04 15:13:03.464 UTC 8a63 INFO[0m [gateway] [34;1mfunc1[0m -> Closing connection to remote endorser address=peer1.org3.example.com:11151 mspid=Org3MSP
[36m2021-11-04 15:13:03.464 UTC 8a64 DEBU[0m [gateway] [36;1mfunc1[0m -> Sending to endorser: channel=mychannel chaincode=basic MSPID=Org2MSP endpoint=peer0.org2.example.com:9051
[36m2021-11-04 15:13:03.464 UTC 8a65 DEBU[0m [gateway] [36;1mfunc1[0m -> Endorse call to endorser failed channel=mychannel txid=4cc6982d9c5aea6f9a5e988dd9f834053353dd858f17f78f8f5b319be4183f34 numEndorsers=1 endorserAddress=peer0.org2.example.com:9051 endorserMspid=Org2MSP error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
[34m2021-11-04 15:13:03.464 UTC 8a66 INFO[0m [gateway] [34;1mfunc1[0m -> Closing connection to remote endorser address=peer0.org2.example.com:9051 mspid=Org2MSP
[36m2021-11-04 15:13:03.464 UTC 8a67 DEBU[0m [gateway] [36;1mfunc1[0m -> Sending to endorser: channel=mychannel chaincode=basic MSPID=Org2MSP endpoint=peer1.org2.example.com:9151
[36m2021-11-04 15:13:03.465 UTC 8a68 DEBU[0m [gateway] [36;1mfunc1[0m -> Endorse call to endorser failed channel=mychannel txid=4cc6982d9c5aea6f9a5e988dd9f834053353dd858f17f78f8f5b319be4183f34 numEndorsers=1 endorserAddress=peer1.org2.example.com:9151 endorserMspid=Org2MSP error="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
[34m2021-11-04 15:13:03.465 UTC 8a69 INFO[0m [gateway] [34;1mfunc1[0m -> Closing connection to remote endorser address=peer1.org2.example.com:9151 mspid=Org2MSP
```

which also shows the connections to the peers being closed because of the context deadline

The transaction was first endorsed on the gateway peer itself
```
2021-11-04 15:12:59.649 UTC 8859 INFO [endorser] callChaincode -> finished chaincode: basic duration: 5351ms channel=mychannel txID=4cc6982d
```

And the txn itself is taken a few seconds
```
{"component":"Chaincode","timestamp":"2021-11-04T15:12:54.309Z","txnId":"4cc6982d9c5aea6f9a5e988dd9f834053353dd858f17f78f8f5b319be4183f34","entryExit":" ENTRY "}
{"component":"Chaincode","timestamp":"2021-11-04T15:12:59.646Z","txnId":"4cc6982d9c5aea6f9a5e988dd9f834053353dd858f17f78f8f5b319be4183f34","entryExit":" EXIT  "}
2021-11-04T15:12:59.646Z info [c-api:lib/handler.js]                              [mychannel-4cc6982d] Calling chaincode Invoke() succeeded. Sending COMPLETED message back to peer
```

This appears to be tied to other peers being killed and restarted but it could be just making collecting all endorsements a longer period.

### PR DESCRIPTION
**Pull request by andrew-coleman**
Currently the options.EndorsementTimeout creates a context that is shared by all endorsement requests in the Endose() and Evaluate() methods.
This commit changes it so It is applied individually to each endorsing peer.
The overall timeout for Endorse/Evaluate is set in the client SDK

Resolves https://github.com/hyperledger/fabric-gateway/issues/292

Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>

### CODE REVIEW

File: internal/pkg/gateway/api.go [hunk 1]
```diff
@@ -63,39 +63,53 @@ func (gs *Server) Evaluate(ctx context.Context, request *gp.EvaluateRequest) (*g
...
+			success, message, retry, remove := gs.responseStatus(pr, err)
+			if success {
+				response = pr.Response
+				// Prefer result from proposal response as Response.Payload is not required to be transaction result
+				if result, err := getResultFromProposalResponse(pr); err == nil {
+					response.Payload = result
+				} else {
+					logger.Warnw("Successful proposal response contained no transaction result", "error", err.Error(), "chaincode", chaincodeID, "channel", channel, "txID", request.TransactionId, "endorserAddress", endorser.endpointConfig.address, "endorserMspid", endorser.endpointConfig.mspid, "status", response.Status, "message", response.Message)
+				}
+				done <- nil
```
Comment (manish-sethi) [inline internal/pkg/gateway/api.go]: This (`done <- nil`) is not needed explicitly (as you don't do this in the `retry` block below).

File: internal/pkg/gateway/api.go [hunk 2]
```diff
@@ -218,6 +244,7 @@ func (gs *Server) Endorse(ctx context.Context, request *gp.EndorseRequest) (*gp.
 			// no more layouts
 			break
 		}
+		var timeoutExpired bool
```
Comment (manish-sethi) [inline internal/pkg/gateway/api.go]: You access this from multiple goroutines so, this needs to be protected. You can either use `mutex` or `sync/atomic` package.

File: internal/pkg/gateway/api_test.go [hunk 3]
```diff
@@ -883,11 +899,41 @@ func TestEndorse(t *testing.T) {
...
+			},
+			timeout: 100 * time.Millisecond,
+			postSetup: func(t *testing.T, def *preparedTest) {
+				peer4Mock.client.(*mocks.EndorserClient).ProcessProposalStub = func(ctx context.Context, proposal *peer.SignedProposal, option ...grpc.CallOption) (*peer.ProposalResponse, error) {
+					time.Sleep(200 * time.Millisecond)
+					return createProposalResponse(t, peer3Mock.address, "mock_response", 200, ""), nil
+				}
+			},
+			errString: "rpc error: code = DeadlineExceeded desc = endorsement timeout expired",
+		},
```
Comment (manish-sethi) [inline internal/pkg/gateway/api_test.go]: These timing based racing tests are prone to add flakes when they run on different hardware (like the first test here) or they add unnecessary delays (like the second test). Can you do change them to somewhat on the following lines...

- Instead of `timeout` store the context in the testdef
- In the mock endorser, call `cancel()` on the `context` and then return after a small wait

Also, can you change the error message slightly so the message from the first endorsement is different  from when you collect the endorsements in parallel - so as to make sure that the error is coming from the intended place.

File: internal/pkg/gateway/api.go (hunk 2 above)
Comment (andrew-coleman) [reply internal/pkg/gateway/api.go]: Thanks.  I've changed it so it passes this flag back via the channel to avoid locking or race condition.

File: internal/pkg/gateway/api_test.go (hunk 3 above)
Comment (andrew-coleman) [reply internal/pkg/gateway/api_test.go]: Made both changes. Thanks!

**Review by manish-sethi — APPROVED** [review]
