### PR TITLE
Fix Orderer test flake #3149

### LINKED ISSUE #3149: Orderer integration test flake
**Failing Stack:**
```
[e][OrdererOrg.orderer1] 2021-12-18 10:24:00.328 UTC 005b INFO [orderer.consensus.etcdraft] catchUp -> Finished syncing with cluster up to and including block [10] channel=systemchannel node=1 
[e][OrdererOrg.orderer1] panic: runtime error: invalid memory address or nil pointer dereference 
[e][OrdererOrg.orderer1] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7230a] 
[e][OrdererOrg.orderer1] 
[e][OrdererOrg.orderer1] goroutine 89 [running]: 
[e][OrdererOrg.orderer1] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).apply(0xc00083a000, 0xc000014f78, 0x1, 0x1) 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:1149 +0xa8a 
[e][OrdererOrg.orderer1] github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).run(0xc00083a000) 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:781 +0x978 
[e][OrdererOrg.orderer1] created by github.com/hyperledger/fabric/orderer/consensus/etcdraft.(*Chain).Start 
[e][OrdererOrg.orderer1] /home/vsts/work/1/fabric/orderer/consensus/etcdraft/chain.go:368 +0x22f
```
**Failing Builds:**
1. https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=45519&view=logs&j=f2000854-c7fb-5d20-d92e-ea22102e0eb5&t=8c0b343e-a113-5c44-d189-698811f88d80
2. https://dev.azure.com/Hyperledger/Fabric/_build/results?buildId=44731&view=logs&j=f2000854-c7fb-5d20-d92e-ea22102e0eb5&t=8c0b343e-a113-5c44-d189-698811f88d80

as per stack frame line no. it is failing here:

https://github.com/hyperledger/fabric/blob/752853701709ce1d5d88db572cacf224ed0e4bd8/orderer/consensus/etcdraft/chain.go#L1147

Based on observation,  block data is empty array which could the reason for the SEGV while dereferencing the entry data as block `b.Header.Number`

```
[e][OrdererOrg.orderer3] 2021-12-30 11:21:21.537 UTC 0041 INFO [orderer.consensus.etcdraft] apply -> DEBUG block raw data:{Term:5 Index:19 Type:EntryNormal Data:[] XXX_unrecognized:[]} channel=systemchannel node=3
```

@guoger It is block type of `EntryNormal`,  can this type of raft entry be empty data & what conditions it can be empty?

In pipeline, it fails randomly. But I see the entry is empty every time with this scenario (ttps://github.com/hyperledger/fabric/blob/752853701709ce1d5d88db572cacf224ed0e4bd8/integration/raft/cft_test.go#L257). This raft entry received just after the orderer restart.  

I confirmed through adding few debug statements above if block. like below:

```
	c.logger.Infof("DEBUG block raw data:%+v", ents[position])
	b := protoutil.UnmarshalBlockOrPanic(ents[position].Data)
	c.logger.Infof("DEBUG %+v\n", b)

	if c.accDataSize >= c.sizeLimit {
```

### PR DESCRIPTION
**Pull request by shivdeep-singh-ibm**
fix #3149  In case of accumulated bytes since last snapshot 
exceed limit while taking snapshot check whether the pb buffer
type is of raftpb.EntryNormal, since blocks are marshalled into 
pb buffers of raftpb.EntryNormal and not raftpb.EntryConfChange

Signed-off-by: Shivdeep Singh <Shivdeep.Singh@ibm.com>

### CODE REVIEW

**Comment by yacovm** [comment]
> [FAB-2835] fix fabric/orderer/common/cluster unit test flakes

But the code fix is not in this package.

**Comment by yacovm** [comment]
> fix Orderer integration test flake

It's a unit test, not an integration test.

**Comment by denyeart** [comment]
I believe the intent is to fix integration test flake described in #3149, even though a new unit test is added here.

@shivdeep-singh-ibm If you use the syntax like #3149 it will automatically link to the issue (The old FAB-xxxx convention was for the previous issue management system in Jira).

If you follow the VerifyBuild failure link, you'll see you need to run 'gofumpt -l -s -w' to fix up chain_test.go.

File: orderer/consensus/etcdraft/chain_test.go [hunk 1]
```diff
@@ -3073,6 +3073,107 @@ var _ = Describe("Chain", func() {
 			})
 
 			Context("failover", func() {
+				It("should check entries applied to raft cluster", func() {
```
Comment (Param-S) [inline orderer/consensus/etcdraft/chain_test.go]: I think, it is more appropriate to add this new unit test case under https://github.com/hyperledger/fabric/blob/35e6f5039d0ded7cfbb6e0d6f76125c430d21587/orderer/consensus/etcdraft/chain_test.go#L2978 this context as it is validating the snapshot condition

File: orderer/consensus/etcdraft/chain_test.go [hunk 2]
```diff
@@ -3073,6 +3073,107 @@ var _ = Describe("Chain", func() {
...
+					})
+
+					By("start the network with new configuration")
+					network.init()
+					network.start()
+
+					network.stop(1)
+					network.elect(2)
+
+					// this section sends proc bype msg apt pos 0
```
Comment (Param-S) [inline orderer/consensus/etcdraft/chain_test.go]: this comment is not very clear. are we trying to induce a raft msg EntryNormal with bytes 0?

**Review by Param-S — CHANGES_REQUESTED** [review]

File: orderer/consensus/etcdraft/chain_test.go (hunk 1 above)
Comment (shivdeep-singh-ibm) [reply orderer/consensus/etcdraft/chain_test.go]: ok.

File: orderer/consensus/etcdraft/chain_test.go (hunk 2 above)
Comment (shivdeep-singh-ibm) [reply orderer/consensus/etcdraft/chain_test.go]: I will remove this line.

File: orderer/consensus/etcdraft/chain.go [hunk 3]
```diff
@@ -1139,9 +1139,12 @@ func (c *Chain) apply(ents []raftpb.Entry) {
 		}
 	}
 
-	if c.accDataSize >= c.sizeLimit {
-		b := protoutil.UnmarshalBlockOrPanic(ents[position].Data)
+	// at postion==0, ents[position].Type is ambiguous, it can be either of {raftpb.EntryNormal, raftpb.EntryConfChange}
+	// take a snapshot only for ents[position].Type == raftpb.EntryNormal
+	isNormalEntry := ents[position].Type == raftpb.EntryNormal
```
Comment (Param-S) [inline orderer/consensus/etcdraft/chain.go]: can we combine this statement into one if condition.  what is the intention of keeping it 2 statements?
> if c.accDataSize >= c.sizeLimit && ents[position].Type == raftpb.EntryNormal && len(ents[position].Data) > 0 {

**Review by Param-S — COMMENTED** [review]
LGTM

**Review by Param-S — APPROVED** [review]

**Comment by Param-S** [comment]
@yacovm @denyeart could you review this PR

**Review by denyeart — APPROVED** [review]
